spring:
  application:
    name: coupon-validation-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: coupon-validation-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: br.com.maxsueleinstein.cuponomia.contracts.event
        spring.json.value.default.type: br.com.maxsueleinstein.cuponomia.contracts.event.CouponChangedEvent

server:
  port: 8082

cuponomia:
  kafka:
    topics:
      coupon-events: coupon.events

resilience4j:
  timelimiter:
    instances:
      checkout-timeout:
        timeout-duration: 2s
        cancel-running-future: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
